version: '3.7'

services:
  # 5.7のイメージをダウンロードしてコンテナを実行
  mysql:
    image: mysql:5.7
    volumes:
      # - ./mysql:/var/lib/mysql
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: 'sample_password'
      MYSQL_DATABASE: sample_db
      # 0.0.0.0で全IPからのアクセス許可
      # BIND-ADDRESS: 0.0.0.0
      # 指定したアドレスで待ち受け
      # BIND-ADDRESS: 192.168.0.XXX
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-time-zone=Asia/Tokyo

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
      - "8080:80"

  php-apache:
    build: ./php
    volumes:
      - ./htdocs:/var/www/html
      - ./cakephp:/var/www/cakephp
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mysql

  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mail
    domainname: example.com
    env_file: mailserver/.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
        #- "143:143"  # IMAP4 (explicit TLS => STARTTLS)
        #- "465:465"  # ESMTP (implicit TLS)
        #- "587:587"  # ESMTP (explicit TLS => STARTTLS)
        #- "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./mailserver/docker-data/dms/mail-data/:/var/mail/
      - ./mailserver/docker-data/dms/mail-state/:/var/mail-state/
      - ./mailserver/docker-data/dms/mail-logs/:/var/log/mail/
      - ./mailserver/docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      TZ: "Asia/Tokyo"
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0


volumes:
    db_data: {}
